version: "2"
services:

  web:
    container_name: "reactAppProduction"
    command: npm run build

  nginx:
    container_name: "nginxProduction"
    ports:
      - "80:80"
    volumes:
      - ./nginx.production.conf:/etc/nginx/nginx.conf:ro
      - ./dist:/var/www/react-weather-fe/dist
